# Generated by Django 4.1.7 on 2023-12-28 07:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_staff",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
